apiVersion: v1
kind: Service

metadata:
  name: appserver-service

spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: appserver
  selector:
    server: appserver